# SCAFFOLD ONLY — not publishable yet (no public release tarball exists).
#
# konsey ships first via a PERSONAL TAP (eMediquality/homebrew-konsey), not
# homebrew-core: core requires notability + a public repo, which do not apply yet.
# Tap layout: a repo named `homebrew-konsey` with this file at `Formula/konsey.rb`,
# then `brew install eMediquality/konsey/konsey`.
#
# When releasing (see RELEASING.md), fill `url` + `sha256` from the GitHub release
# tag, then run `brew update-python-resources Formula/konsey.rb` to GENERATE the
# `resource` stanzas for langgraph / langchain-core / duckdb / pydantic and their
# transitive deps (do NOT hand-write them).
class Konsey < Formula
  include Language::Python::Virtualenv

  desc "Multi-agent, evidence-weighted, vendor-independent work orchestrator"
  homepage "https://github.com/eMediquality/konsey"
  # TODO(release): real tag tarball + its sha256 (curl -sL <url> | shasum -a 256)
  url "https://github.com/eMediquality/konsey/archive/refs/tags/vX.Y.Z.tar.gz"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  license "Apache-2.0" # code license; the doctrine text is CC-BY-4.0 (see NOTICE)

  depends_on "python@3.12"

  # TODO(release): generated by `brew update-python-resources` — leave empty until then.
  # resource "langgraph" do ... end
  # resource "pydantic"  do ... end

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "konsey", shell_output("#{bin}/konsey --version")
  end
end
